pipeline:
  build:
    image: node:10.4
    commands:
      - npm install yarn
      - yarn
      - cp .evn.example .env
      - yarn test --verbose --coverage=true --forceExit
  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [success, failure]
      event: [push, tag]
