// locationTypes action types
export const LOCATIONTYPES_FETCHED = 'locationTypes.LOCATIONTYPES_FETCHED';
export const LOCATIONTYPE_CREATED = 'locations.LOCATIONTYPE_CREATED';
export const LOCATIONTYPE_FETCHED = 'locations.LOCATIONTYPE_FETCHED';
export const LOCATIONTYPE_EDITED = 'locations.LOCATIONTYPE_EDITED';
export const LOCATIONTYPE_DELETED = 'locations.LOCATIONTYPE_DELETED';
export const LOCATIONTYPES_CHANGE_PAGE = 'locationTypes.LOCATIONTYPES_CHANGE_PAGE';
